"""
Figure 8: Cyber-Physical Interference Viability Curve.

Loads the raw per-pipeline T_comp points (Culex_Transit reference row,
read directly from the two raw baseline CSVs) and the deterministic
escape-boundary curve rows from
``data/csv/figure8_survival_probability.csv`` and renders Figure 8 in
PNG / PDF / SVG at 600 DPI (PNG) with vector PDF and SVG outputs.

The CSV is generated by ``evaluation/build_figure8_data.py`` from
the raw Culex_Transit measurements in
``data/csv/table1_semantic_baselines.csv`` and
``data/csv/table1_baselines.csv``; no manuscript-locked,
hand-edited or hard-coded values are used anywhere in the data flow.

The figure has no embedded title (caption is supplied in the
manuscript, per the EAAI submission guidelines). Five pipeline
markers are laid out with leader-line annotations so the upper-left
region has no overlap.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = ['DejaVu Sans', 'Arial']
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['axes.linewidth'] = 1.2
plt.rcParams['font.size'] = 11
plt.rcParams['figure.dpi'] = 600
plt.rcParams['savefig.dpi'] = 600

THIS_DIR = Path(__file__).resolve().parent
DATA_CSV = THIS_DIR.parent / "data" / "csv" / "figure8_survival_probability.csv"


def _load_survival_csv(csv_path):
    """Load figure-8 data from ``csv_path``.

    Lines starting with ``#`` (after optional leading whitespace) are
    treated as comments and skipped, so the data file can carry a
    provenance header. The first non-comment line is the header row.
    """
    import csv
    curve_T, curve_P = [], []
    pipelines = {}
    with open(csv_path, "r", newline="") as f:
        header = None
        for line in f:
            stripped = line.lstrip()
            if not stripped or stripped.startswith("#"):
                continue
            cells = next(csv.reader([line.rstrip("\r\n")]))
            if header is None:
                header = cells
                continue
            row = dict(zip(header, cells))
            t = float(row['T_comp_ms'])
            p = float(row['P_capture_percent'])
            kind = row.get('Pipeline', 'Curve').strip()
            if kind.lower() == 'curve':
                curve_T.append(t)
                curve_P.append(p)
            else:
                pipelines[kind] = (t, p)
    return curve_T, curve_P, pipelines


def create_figure8():
    if not DATA_CSV.exists():
        raise FileNotFoundError(f"Missing: {DATA_CSV}")

    curve_T, curve_P, pipelines = _load_survival_csv(DATA_CSV)
    order = np.argsort(curve_T)
    curve_T = np.array(curve_T)[order]
    curve_P = np.array(curve_P)[order]

    fig, ax = plt.subplots(figsize=(8, 5), dpi=600)

    ax.plot(curve_T, curve_P, color='black', lw=2,
            label='Deterministic P_capture Bound')
    ax.axhline(y=95.0, color='gray', linestyle='--', lw=1,
               label='95% Biosecurity Threshold')
    ax.axvline(x=75.0, color='gray', linestyle=':', lw=1,
               label=r'$T_{allow}$ = 75.0 ms Limit')

    ax.axvspan(0, 19.5, color='green', alpha=0.08)
    ax.axvspan(19.5, 75.0, color='red', alpha=0.05)

    style = {
        'MOG2 + Lucas-Kanade':  dict(marker='X', color='#e08e0b',
                                      xytext=(-90, 22),  va='bottom', ha='right'),
        'MOG2 + SORT':          dict(marker='X', color='#1f6feb',
                                      xytext=(12, 30),   va='bottom', ha='left'),
        'STMSS (Proposed)':     dict(marker='o', color='#1a7f37',
                                      xytext=(15, -32),  va='top',    ha='left'),
        'MOG2 + IMM (2-Model)': dict(marker='X', color='#7e3af2',
                                      xytext=(-25, -45), va='top',    ha='right'),
        'YOLOv8n + ByteTrack':  dict(marker='X', color='#cf222e',
                                      xytext=(15, 8),    va='bottom', ha='left'),
    }
    for name, (t, p) in pipelines.items():
        s = style.get(name, dict(marker='o', color='black',
                                 xytext=(0, 10), va='bottom', ha='center'))
        ax.scatter(t, p, marker=s['marker'], color=s['color'], s=85,
                   edgecolor='black', linewidth=0.6, zorder=5)
        ax.annotate(f"{name}\n(T={t} ms, P={p:.1f}%)",
                    xy=(t, p), xytext=s['xytext'],
                    textcoords='offset points',
                    ha=s['ha'], va=s['va'],
                    fontsize=8, weight='bold', color=s['color'],
                    arrowprops=dict(arrowstyle='-', color=s['color'],
                                    lw=0.7, alpha=0.8))

    ax.set_xlim(0, 78)
    ax.set_ylim(-5, 105)
    ax.set_xlabel(r'Isolated Pipeline Latency $T_{comp}$ (ms)',
                  fontsize=10, weight='bold')
    ax.set_ylabel(r'Capture Probability $P_{capture}$ (%)',
                  fontsize=10, weight='bold')
    ax.grid(True, linestyle=':', alpha=0.5)

    leg = ax.legend(loc='lower left', fontsize=8, frameon=True,
                    facecolor='white', edgecolor='lightgray')
    leg.set_zorder(20)

    plt.tight_layout()
    for ext, dpi in (('png', 600), ('pdf', None), ('svg', None)):
        plt.savefig(THIS_DIR / f'Figure8_Survival_Probability.{ext}',
                    bbox_inches='tight', facecolor='white', dpi=dpi)
    plt.close(fig)
    print("Figure 8 written (Figure8_Survival_Probability.png/pdf/svg)")


if __name__ == "__main__":
    create_figure8()
